### ISSUE TITLE
Using ApplySyntax with built-in syntax selections

### ISSUE THREAD

**Issue by sybercorp** [facelessuser/ApplySyntax#101]
How do I use ApplySyntax with the built-in syntax selections rather than only ones installed into the downloaded Packages folder?  For example, if I want to use the built in Regular Expression syntax, which is located at "C:\Program Files\Sublime Text 3\Packages\Regular Expression.sublime-package", rather than "C:\Users\<username>\AppData\Roaming\Sublime Text 3\Installed Packages", how would I accomplish that?

**Comment by facelessuser** [comment]
I guess I don't fully understand the question, but I'll say this, whether it is a default package, or a package installed in `Installed Packages`, or a package in `Packages`, the method is the same.  You will always reference packages as `Packages\<package folder or zip>\<folders to syntax>\<syntax file minus extension>`.  ApplySyntax abstracts all that so all you have to do is use the same format.

If you are in a situation where you have a duplicate in `Installed Packages` and one in `Packages`, Sublime is defaults to the one in `Packages` and that overrides the `Installed Packages` one.

Please see [documentation](http://facelessuser.github.io/ApplySyntax/usage/#creating-rules) for more details.

**Comment by sybercorp** [comment]
The documentation says the path is relative to Packages though, so wouldn't it look in the Packages folder that ApplySyntax is in instead of the other Packages folder which is in the application installation path?  You'd have to go back folders like ../../Program Files, or something, wouldn't you? Or does it look in all locations for a match to what you're calling?

Jesse Peden
Threema ID: 9JY6YPKR (threema://add?id=9JY6YPKR)
sybercorp@gmail.com
PGP Public Key: https://pgp.mit.edu/pks/lookup?op=get&search=0xE8C3FBF61B77E621
PGP Public Key Fingerprint: D669 3CE1 8688 BE2E A42A  14BE E8C3 FBF6 1B77 E621
(Sent from a mobile device - please excuse any typos or brevity)

**Comment by facelessuser** [comment]
Yeah, sorry, I'm being confusing:

You enter:

```
<package folder or zip>\<folders to syntax>\<syntax file 
```

not 

```
Packages\<package folder or zip>\<folders to syntax>\<syntax file 
```

What I'm trying to illustrate is all packages are referenced **as if** they were all in `Packages`.  That is what Sublime does.  You have default packages, installed packages, and normal packages.  But `Packages` overrides `Installed Packages` and `Default`, and `Installed Packages` override just `Default`.

So internally Sublime kinda merges all these different folders into one `Packages` folder.  You can create a folder under `Packages` that matches a package name in `Installed Packages` and override just 1 file.  It all just gets merged together.  So Sublime and ApplySyntax takes care of all of that and loads the file that should get loaded.  So, no matter where things are installed: `Default`, `Installed Packages`, or `Packages`, we assume it all in `Packages`.

So you don't have to step out with `..\..`.  Just pretend everything is merged in `Packages` and so everything is then just relative to `Packages`:

```
<package folder or zip>\<folders to syntax>\<syntax file minus extension>
```

**Comment by sybercorp** [comment]
That makes sense so can you tell me what I'm doing wrong to chase this not to work?

I'm trying to use the built-in Regular Expressions syntax which is in the installation root of Sublime Text in its packages folder, so in my ApplySyntax user settings file I've got:

{
"syntax": "Regular Expressions/RegExp",
"rules": [
{"first_line": "^#regex"}
]
}

It isn't switching the syntax to Regular Expression upon saving though, even with the hashtag header.

Jesse Peden
Threema ID: 9JY6YPKR (threema://add?id=9JY6YPKR)
sybercorp@gmail.com
PGP Public Key: https://pgp.mit.edu/pks/lookup?op=get&search=0xE8C3FBF61B77E621
PGP Public Key Fingerprint: D669 3CE1 8688 BE2E A42A  14BE E8C3 FBF6 1B77 E621
(Sent from a mobile device - please excuse any typos or brevity)

**Comment by sybercorp** [comment]
I re-launched Sublime Text and now it's working.  Does ApplySyntax only look at what syntax files it's going to need upon launch (when it first reads the settings file), meaning if you add something to it you have to re-launch Sublime Text before it'll take effect?

**Comment by facelessuser** [comment]
No, updating the settings file should affect future file opens and saves **without** needing to restart Sublime.

**Comment by sybercorp** [comment]
Hmm. Well, it didn't. That's all I ended up doing and it started working. Weird.  Oh well. Thanks for the help.

**Comment by facelessuser** [comment]
Something was probably in a weird state on your machine, but when I confirmed your settings work, I modified my settings without restarting Sublime.  That is handled by the Sublime API, not ApplySyntax.  Plugins rely on settings updating proper through the API.
