### ISSUE TITLE
Sublime keep changing my setting files, removing '*.inc' files from 'AmxxPawn' and adding it as 'PHP'.

### ISSUE THREAD

**Issue by evandrocoan** [facelessuser/ApplySyntax#102]
The details are described here: https://github.com/SublimeTextIssues/Core/issues/1333

**Comment by facelessuser** [comment]
This is not a bug, but how it is intended to work.  See the rule: https://github.com/facelessuser/ApplySyntax/blob/master/ApplySyntax.sublime-settings#L139.

If you don't like the default rule, configure it how you would like it by overriding it.  If you can give a convincing argument as to why it shouldn't be defaulted to PHP by default, we can remove it.

Please read the docs to learn how to configure your own personal rules: http://facelessuser.github.io/ApplySyntax/usage/#creating-rules.

Rules are managed by the community via pull requests, I just maintain the framework (though I step in when bad rules step on how I use it).

**Comment by evandrocoan** [comment]
I can see and understand perfectly. It forces predefined extensions, always overriding the user settings, over, and over again. The only way I use this package is editing the source code by myself. Not good. 

You could add this to the first page:
```
It forces predefined extensions, always overriding the user settings. To use different extensions, you must edit the package source code my yourself. For example, if you need only '*.inc' files being used as anything else than PHP.
```

**Comment by facelessuser** [comment]
> The only way I use this package is editing the source code by myself.

You are mistaken, you do not edit the package **source**, you edit the **settings file**.  You simply drop a setting setting file with the same name in your User folder and override.  This is quite sensible.  If you have a strong argument that supports that `*.inc` should not be a default rule, let me know.  It can be removed if it is problematic via a pull request (just update the setting file, no "source code" needs to be touched).

**Comment by evandrocoan** [comment]
> You are mistaken

You right, I overlooked too quickly.
