### ISSUE TITLE
ApplySyntax with php

### ISSUE THREAD

**Issue by grinsteindavid** [facelessuser/ApplySyntax#104]
from the terminal: 
ApplySyntax: Syntax file for PHP does not exist at Packages/PHP/PHP.sublime-syntax
ApplySyntax: Syntax file for PHP does not exist at Packages/PHP/PHP.tmLanguage

**Comment by facelessuser** [comment]
It sounds like those syntax don't exist or are disabled.  You may need to either enable them or define a different syntax in your user files.  You can also open a pull request appending the additional PHP syntax that can be used to the existing PHP rule.  See the documentation for more info.

**Comment by facelessuser** [comment]
As I haven't heard any response, I am assuming you figured out your issue.  I am closing this.
