### ISSUE TITLE
[Feature request] Change folder for add_exts_to_lang_settings

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/ApplySyntax#109]
### Request

It would be nice, if you add opportunity change folder for `add_exts_to_lang_settings`.

### Justification

Part of my `User` folder:

![My sidebar](http://i.imgur.com/67xADUe.png)

Besides `.sublime-settings` files, generate by ApplySyntax, I have in `User `folder many other files. If `.sublime-settings` files add in my `User` folder, I'm getting more complicated navigate in my `User` folder. This disorder.

### Extended behavior

For example, add in ApplySyntax new parameter: `"add_exts_to_lang_settings_path":`, default value is `"Packages/User/ApplySyntaxSettingsFiles"`.

Thanks.

**Comment by facelessuser** [comment]
Settings have to be loaded from the root of users.  That's just how the API works in Sublime.  Unfortunately, I don't think there is anything I can do about this..  As much as I'd like to keep all these settings tidy and put them in their own folder, if I do that, I won't get the auto-refresh of settings changes without coding up my settings monitor.

**Comment by facelessuser** [comment]
Let me look at the code first and refresh myself on how I use the file before I give a final answer.  If I don't care about an auto-refresh, maybe I can move it.

**Comment by facelessuser** [comment]
It's been a year and I clearly haven't done this.  I think it is safe to say I'm probably not doing this. I am going to go ahead and close this issue.
