### ISSUE TITLE
Lists of syntaxes not behaving properly

### ISSUE THREAD

**Issue by wmwolf** [facelessuser/ApplySyntax#112]
From the documentation:

> If it is desirable for the syntax rule to reference multiple tmLanguage files because it is not known which package will be on a machine, you can set the syntax as an array of syntaxes as shown in the following example. The first one found will be used.

> `"syntax": ["RSpec/RSpec", "RSpec (snippets and syntax)/Syntaxes/RSpec"]`

However, when using lists of syntaxes, several unexpected things happen. First, it seems that each syntax is tried, regardless if the first one is found. Looking at the logs after loading an Rspec file, I see the following:

    Switched syntax to: RSpec
    ApplySyntax: Syntax file for RSpec does not exist at Packages/RSpec/RSpec.sublime-syntax
    ApplySyntax: Syntax already set to Packages/RSpec/RSpec.tmLanguage
    ApplySyntax: Syntax file for RSpec does not exist at Packages/RSpec (snippets and syntax)/Syntaxes/RSpec.sublime-syntax
    ApplySyntax: Syntax file for RSpec does not exist at Packages/RSpec (snippets and syntax)/Syntaxes/RSpec.tmLanguage
    ApplySyntax: Syntax file for Better RSpec does not exist at Packages/Better RSpec/Better RSpec.sublime-syntax
    ApplySyntax: Syntax file for Better RSpec does not exist at Packages/Better RSpec/Better RSpec.tmLanguage

Since the first choice (RSpec/RSpec.tmLanguage) was found, I would think it should stop there. Indeed, trying to load a file with multiple matching (installed) syntaxes seems to prefer the _last_ syntax rather than the first. Not a big deal, as I can just rearrange my list, but this is still unintuitive.

More concerning is that providing a list of syntaxes seems to break the `add_exts_to_lang_settings` option upon reloading settings. It throws an error of how lists don't have the `rfind` method:

    {
        "syntax": ["Fortran/grammars/FortranModern", "MinimalFortran/MinimalFortran"],
        "extensions": ["f", "f90", "inc", "dek"]
    }

throws

    reloading settings Packages/User/ApplySyntax.sublime-settings
    Traceback (most recent call last):
      File "ApplySyntax in /Users/wmwolf/Library/Application Support/Sublime Text 3/Installed Packages/ApplySyntax.sublime-package", line 657, in on_reload
      File "ApplySyntax in /Users/wmwolf/Library/Application Support/Sublime Text 3/Installed Packages/ApplySyntax.sublime-package", line 235, in update_extenstions
      File "./python3.3/posixpath.py", line 125, in splitext
      File "./python3.3/genericpath.py", line 92, in _splitext
    AttributeError: 'list' object has no attribute 'rfind'

 This seems to be rooted in the `update_extensions` function, which attempts to call `splitext` on whatever is held in `"syntax"`. We probably just need to check if the `"syntax"` key holds an iterable and if so, walk through it. I can't figure out why this problem doesn't bother the baked-in RSpec syntaxes, though, so I might be missing something.

**Comment by facelessuser** [comment]
Thanks for the details! I will take a look at this sometime soonish.  I there is enough info here to debug and fix the issue.

**Comment by facelessuser** [comment]
This bug was introduced back with the new syntax format.  We used to break out of the for loop when we set the syntax, but we added a nested for loop that loops through the new and old syntax format looking for which is available.  Breaking out of both loops was missed, so we only break out of the syntax type loop and not the parent syntax loop.

The extension issue was completely missed.

**Comment by facelessuser** [comment]
It turns out we lower case the file extension, but expect the extension in the rules is already lower case. By using `tmpreferences` instead of `tmPreferences`, your rule works.
