### ISSUE TITLE
You broke my configuration :/

### ISSUE THREAD

**Issue by timmyrs** [facelessuser/ApplySyntax#113]
I pretty much only used ApplySyntax to detect `.js.php` and `.css.php` as JavaScript and CSS respectively.
I got the original configuration for this from [this SuperUser answer](https://superuser.com/a/621557/602655), however, I noticed it didn't work anymore, so I tried to change `name` to `syntax` and `file_name` to `file_path`, but it still doesn't work.
How can I get this to work again?
PS: You wrote "extenstions" in the settings files.

**Comment by facelessuser** [comment]
> You broke my configuration :/

Did I?  Or did your configurations not keep up?  😏.

1. Anyways, go in your menu to `Preferences->Package Settings->ApplySyntax->Support Info` and post that here.

2. Post your actual Apply Syntax settings here.

3. Post links to the the syntax languages you have installed (unless they are default syntaxes that are shipped with Sublime).

Once that is posted, I can take a closer look.

**Comment by timmyrs** [comment]
> - ST ver.: 3143
> - Platform: windows
> - Arch: x64
> - Plugin ver.: 2.5.0
> - Install via PC: True
> - mdpopups ver.: 3.3.0
> - markdown ver.: 2.6.9
> - pygments ver.: 2.1a0
> - jinja2 ver.: 2.8

```
{
    // If you want exceptions reraised so you can see them in the console, change this to true.
    "reraise_exceptions": false,

    // If you want to have a syntax applied when new files are created, set new_file_syntax to the name of the syntax
    // to use.  The format is exactly the same as "syntax" in the rules below. For example, if you want to have a new
    // file use JavaScript syntax, set new_file_syntax to 'JavaScript'.
    "new_file_syntax": false,

    // Auto add extensions to language settings file in User folder.
    // Do not manually remove "apply_syntax_extensions" from the settings file.
    // "extenstions" are ignored by "match": "all" setting.
    "add_exts_to_lang_settings": true,

    // Control level of logging in the console.
    // (true|false|"verbose")
    "debug": true,

    // Put your custom syntax rules here:
    "syntaxes": [
      {
        "syntax": "JavaScript/JavaScript",
        "rules": [
          {"file_path": ".*\\.js\\.php$"}
      ]
    },
    {
        "syntax": "CSS",
        "rules": [
          {"file_path": ".*\\.css\\.php$"}
      ]
    }
]
}
```

Notice the "extenstions"

**Comment by facelessuser** [comment]
```
{
    "syntaxes": [
        {
            "syntax": "JavaScript/JavaScript",
            "extensions": ["js.php"]
        },
        {
            "syntax": "CSS/CSS",
            "extensions": ["css.php"]
        }
    ]
}
```

This also worked for me

```
{
    "syntaxes": [
        {
            "syntax": "JavaScript/JavaScript",
            "rules": [
                {"file_path": ".*\\.js\\.php$"}
            ]
        },
        {
            "syntax": "CSS/CSS",
            "rules": [
                {"file_path": ".*\\.css\\.php$"}
            ]
        }
    ]
}
```

**Comment by timmyrs** [comment]
It didn't work with `"syntax": "CSS"`, for some reason it had to be "CSS/CSS". Now it works, thanks.

**Comment by facelessuser** [comment]
> It didn't work with "syntax": "CSS", for some reason it had to be "CSS/CSS". Now it works, thanks.

This is covered in the documents: http://facelessuser.github.io/ApplySyntax/usage/#syntax.

Please read it to learn how to configure ApplySyntax.
