### ISSUE TITLE
Cannot change any setting in ApplySyntax.sublime-setting - ApplySyntax

### ISSUE THREAD

**Issue by cptalpdeniz** [facelessuser/ApplySyntax#114]
I'm trying to change the setting for new_file_syntax as I only use C++ it would automatically apply C++ syntax. However, I cannot change any setting in ApplySyntax.sublime-setting - ApplySyntax whereas I can in ApplySyntax.sublime-setting - User. I already changed the setting in User but it doesn't apply anything to new files so I don't know what the exact problem is here.

**Comment by facelessuser** [comment]
>  I cannot change any setting in ApplySyntax.sublime-setting

Of course you can't, you're supposed to override it in your User settings.

> I already changed the setting in User but it doesn't apply anything to new files so I don't know what the exact problem is here.

Most likely you've set the setting incorrectly.

What did you set it to?  And are you using the default C++ syntax, or a third party syntax?  Please provide as much detail as possible.
