### ISSUE TITLE
Help with custom syntax rules

### ISSUE THREAD

**Issue by ngocphamm** [facelessuser/ApplySyntax#118]
I have tried my best reading the documentation but I still can't get what I want.

```
- ST ver.: 3175
- Platform: osx
- Arch: x64
- Plugin ver.: 2.5.1
- Install via PC: True
- mdpopups ver.: 3.3.3
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8
```

My syntax rules
```
        {
            "syntax": "ShellScript/Shell-Unix-Generic",
            "rules": [
                {"file_path": ".*\\.env.*$"},
                {"file_path": "zpreztorc$"}
            ]
        },
        {
            "syntax": "Tmux Syntax Highlight/Tmux",
            "rules": [
                {"file_path": "^\\.tmux\\.mac\\.conf$"}
            ]
        }
```

And this is ApplySyntax's verbose log
```
ApplySyntax: Updating Extensions
ApplySyntax: Found Extensions: MXML - ['mxml']
ApplySyntax: Found Extensions: XML/XML - ['xml.dist']
ApplySyntax: Found Extensions: Rails/HTML (Rails) - ['html.erb']
ApplySyntax: Found Extensions: Rails/Ruby Haml - ['haml']
ApplySyntax: Found Extensions: Ruby/Ruby - ['thor', 'rake', 'simplecov', 'jbuilder', 'rb', 'podspec', 'rabl']
ApplySyntax: Found Extensions: Ruby Slim/Syntaxes/Ruby Slim - ['emblem']
ApplySyntax: Found Extensions: Blade/Blade - ['blade.php']
ApplySyntax: Found Extensions: PHP/PHP - ['php3', 'php4', 'php5', 'inc', 'phtml']
ApplySyntax: Found Extensions: PHP/Smarty - ['tpl']
ApplySyntax: Found Extensions: YAML/YAML - ['.gemrc', 'yml', 'yml.dist', 'YAML-tmLanguage']
ApplySyntax: Found Extensions: INI/INI - ['.gitattributes', '.gitconfig', '.gitignore', 'ini.dist', '.npmrc']
ApplySyntax: Found Extensions: ShellScript/Shell-Unix-Generic - ['bash', 'sh', 'zsh']
ApplySyntax: Found Extensions: Python/Python - ['py3', 'pyw']
ApplySyntax: Found Extensions: JavaScript/JSON - ['.jshintrc', '.jscsrc', '.csslintrc', '.eslintrc', '.bowerrc', 'geojson']
ApplySyntax: Found Extensions: Laravel Blade Highlighter/laravel-blade - ['blade.php']
ApplySyntax: Prunning Extensions
ApplySyntax: Language Hash - '7062001247868596732'
ApplySyntax: Language Hash - '7062001247868596732'
ApplySyntax: Language Hash - '7062001247868596732'
ApplySyntax: Language Hash - '7062001247868596732'
ApplySyntax: Language Hash - '7062001247868596732'
```

The last 5 lines was when I closed and reopened `.tmux.mac.conf` and `.zpreztorc` files. None of the 2 files got applied with syntax. Other files like `.tmux.conf`, or `.zshrc` get syntax set properly.

**Comment by facelessuser** [comment]
Sorry I haven't gotten to this.  I'll take a look sometime soon.  I've just been busy.

**Comment by ngocphamm** [comment]
That's not a problem! Thanks in advance! 👍

**Comment by facelessuser** [comment]
Can you let me know what your file structure looks like that you are testing this on?  I need to know not only what your configuration is, but what you are testing it on so I can reproduce.

**Comment by ngocphamm** [comment]
It's a Sublime project with the following folders in it

```
{
	"folders":
	[
		{
			"path": "/usr/local/etc"
		},
		{
			"path": "/Users/ngoc/.config"
		},
		{
			"path": "/Users/ngoc/.zprezto"
		}
	]
}
```

I also have a bunch of files dragged and dropped to ST, like `.zshrc`, `.zprofile`, and `.zpreztorc`. The first 2 files got syntax applied, but not the last one.

**Comment by facelessuser** [comment]
Your patterns aren't sufficient.  To match `.zpreztorc`, you'd have to use something like:

```
{"file_path": ".*//.zpreztorc$"}
```

If all `.zshrc`, `.zprofile`, and `.zpreztorc` should get matched, regardless of location, you can skip all the `file_path` stuff and just use extensions, see [`.gitignore` in the default settings](https://github.com/facelessuser/ApplySyntax/blob/master/ApplySyntax.sublime-settings#L157).

There are a lot of examples in the default settings that are similar to what you are trying to do, take a look there.  Just remember, if you are trying to use `file_path`, imagine getting the whole path, with file name, and you have to match the whole thing.

**Comment by ngocphamm** [comment]
The `file_path` rule you posted still didn't work, but I switched to `extensions` and it's good now. Thank you!

**Comment by facelessuser** [comment]
It didn't work because I did double forward slashes by accident. I meant one of those to be a backslash to escape the dot. Clearly I didn't test it, but I was mostly trying to illustrate that the file path must match the whole path.

Anyways, glad you got our working.
