### ISSUE TITLE
New release for Package Control?

### ISSUE THREAD

**Issue by Phidica** [facelessuser/ApplySyntax#123]
I see some pretty good quality-of-life fixes unreleased on master, with the last commit a month ago preparing for a new release. Will this be created soon?

**Comment by facelessuser** [comment]
It's in the plan, I maintain a bunch of stuff, so my focus pulls from some areas sometimes longer than intended.

**Comment by michaelblyons** [comment]
@facelessuser I think you forgot to [`st3-`prefix the tag][1] on the last release. 😉 

[1]: https://github.com/wbond/package_control_channel/blob/master/repository/a.json#L1502-L1510

**Comment by facelessuser** [comment]
Ah, you are correct. I forget occasionally when doing Sublime specific releases.

**Comment by facelessuser** [comment]
Release has been corrected. Thanks for the heads up!
