### ISSUE TITLE
Override XML rule for tmPreferences

### ISSUE THREAD

**Issue by michaelblyons** [facelessuser/ApplySyntax#125]
I have the venerable [PackageDev][] package installed, which has some specialty language definitions. Unfortunately, ApplySyntax overrides one of them ([the one for `.tmPreferences` files][tmPreferences]) and sets it to XML with the default rules. I'd like to override it back in my User Settings' rules, but I can't seem to get it to work. I've tried these things so far:

```jsonc
    syntaxes: [
        // If you have PackageDev installed, use it for tmPreferences files.
        // If not, fall back to XML.
        {
            "syntax": [
                "PackageDev/TextMate Preferences/TextMate Preferences",
                "XML/XML",
            ],
            "extensions": ["tmPreferences"],
        },
        {
            "syntax": [
                "PackageDev/TextMate Preferences (PList / XML)",
                "XML/XML",
            ],
            "extensions": ["tmPreferences"],
        },
        ...
    ]
```

I'm curious why you even need the `first_line` rule in the `default_syntaxes`. It basically duplicates [the first line matching][flm] already in `XML.sublime-syntax`.

[PackageDev]: https://packagecontrol.io/packages/PackageDev
[tmPreferences]: https://github.com/SublimeText/PackageDev/blob/master/Package/TextMate%20Preferences/TextMate%20Preferences.sublime-syntax
[flm]: https://github.com/sublimehq/Packages/blob/master/XML/XML.sublime-syntax#L13-L18

**Comment by facelessuser** [comment]
Pretty sure I inherited that rule when I took over ApplySyntax, but I could be wrong. I'll take a look when I get a chance and get back to you. I need to refresh on overrides.

**Comment by michaelblyons** [comment]
Turns out, none of these work:

``` jsonc
        {
            // If you have PackageDev installed, use it for tmPreference files
            "syntax": [
                "PackageDev/TextMate Preferences",
                "PackageDev/TextMate Preferences (PList / XML)",
                "PackageDev/TextMate Preferences/TextMate Preferences",
                "TextMate Preferences",
                "TextMate Preferences (PList / XML)",
                "TextMate Preferences/TextMate Preferences",
                "XML/XML",
            ],
            "extensions": ["tmPreferences"],
        },
```

**Comment by facelessuser** [comment]
I'm not sure how easy it is to override. User rules may just append, I'll have to check. Just haven't had a chance yet.

**Comment by michaelblyons** [comment]
> User rules may just append

Nuts, you're right. I am very opinionated that the order should be switched so user rules come first.

https://github.com/facelessuser/ApplySyntax/blob/0faad8ee6ec13b15c74375b5198137a804054cd5/ApplySyntax.py#L226-L227

**Comment by facelessuser** [comment]
I didn't come up with the current design. I'm not the original author. I think the original idea was that the default rules were universally desired.

I mean we could add a package dev rule. We could also overhaul the current rule system to be more flexible.
