### ISSUE TITLE
Can't make Groovy extension work on Jenkinsfile

### ISSUE THREAD

**Issue by gmaggess** [facelessuser/ApplySyntax#140]
I either don't understand how it works or it's a bug in ApplySyntax. I'm trying to apply Groovy syntax to Jenkinsfiles and it doesn't seem to work:

    "syntaxes": [
        {
            "syntax": "Groovy/Groovy",
            "extensions": ["groovy"],
            "rules": [
                {"file_path": "^Jenkinsfile\\w*"}
            ]
        },
    ]

Any clues?

**Comment by facelessuser** [comment]
You are evaluating a file path, but the pattern you are using makes me think you assume it is evaluating just the file name and not the full path?

**Comment by gmaggess** [comment]
Correct! I want filenames starting with Jenkinsfile to be assigned to groovy syntax.

**Comment by facelessuser** [comment]
You'll have to construct the pattern to look for a file then. Something like `.*[\\\\/]Jenkinsfile\\w*$`

**Comment by facelessuser** [comment]
I'm assuming the question has been answered. Feel free to reopen if you are still having questions.
