### ISSUE TITLE
Unintuitve resolution of syntax names

### ISSUE THREAD

**Issue by mvastola** [facelessuser/ApplySyntax#141]
I really find this plugin useful, but I also just spent an hour debugging an issue that seems to be caused by the [set_syntax](https://github.com/facelessuser/ApplySyntax/blob/a29fedfe7ce6ae054bdb5ef43518712c72954fdf/ApplySyntax.py#L451) function. 

My first hurdle was in locating this issue: 
It seems that if your `ApplySyntax` settings refer to a syntax that can't be located, the `ApplySyntax` rule silently (even with `verbose` debugging) fails to apply. 

It's perhaps understandable to not produce any messages if a number of syntaxes were given in an array and one fails (after all, the point of an array is that only one of them needs to be installed), though it might still be a good idea. However, when the config only lists one syntax and it can't be found (or multiple, and none could be found) it would be helpful if a warning of some sort could be emitted.

The other issue is that without looking at the code or thoroughly reading [the docs](http://facelessuser.github.io/ApplySyntax/usage/#syntax) at online, there is no indication a path name is expected. Instead, I just assumed the `syntax` key should just contain the name of the entry in the `View -> Syntax` menu.  I'd like to request that a comment explaining this be added to the default user `sublime-settings` file. (Ideally it would be great if the syntax could be looked up by its menu entry, but I'm not sure if the API exposes that list.)

Thanks a lot.

**Comment by facelessuser** [comment]
> It seems that if your ApplySyntax settings refer to a syntax that can't be located, the ApplySyntax rule silently (even with verbose debugging) fails to apply.

We could make it log a note if debug is verbose. I wouldn't have a problem accepting a pull request with this.

> The other issue is that without looking at the code or thoroughly reading the docs at online, there is no indication a path name is expected.

That's why I wrote the docs, to explain the behavior. Unfortunately, people don't like to read docs, but I can't help that 🤷. I guess if we could do it all over again, naming it `syntax_path` would have made it more intuitive. Hindsight is 20/20 and all that 🙂 

With all of that said, if you can find a spot in the settings that people are likely to look, I'm open to a pull request that includes this information. The default settings have a lot of entries, I'm not sure there is one specific entry which would stand out to most users with this information, maybe at the start of the structure? I'm willing to do this though.

**Comment by mvastola** [comment]
Yeah, I'll work on something for if debug is verbose. I was thinking this could be mentioned before the `syntax` structure too. 

The reason (I at least) didn't look at the docs was because all of the examples seemed to follow the pattern of the syntax matching the path in the `View -> Syntax` menu structure, so it didn't occur to me that that wasn't correct. I'm guessing that naming syntax files to match this is a convention that's not always followed.

It's annoying that Sublime's API is really lacking with regard to accessing loaded syntaxes, because it'd probably be too much overhead to find the names in all syntax files, but allowing those would be by far the most graceful option.

**Comment by facelessuser** [comment]
```py
>>> sublime.active_window().active_view().settings().get('syntax')
'Packages/Python/Python.sublime-syntax'
```

With that said, maybe a helper function that retrieves this info could be helpful 🤔 .

**Comment by mvastola** [comment]
Actually, I just found [this](https://sublimetext.github.io/sublime_lib/#sublime_lib.list_syntaxes) What do you think? Haven't checked how exactly it works, but this seems like a very clean solution.

The only issue with `sublime.active_window().active_view().settings().get('syntax')` is you can only get the currently set syntax (and to set a different syntax you need the actual path. (In other words, this could only work if you already have the syntax set correctly, in which case you don't need this plugin.)

...unless you were suggesting caching every syntax encountered, one at a time. (Which could work but could lead to more confusion if someone copies their config somewhere and hasn't otherwise used the syntax. 

Something that also occurred to me was using `sublime.find_resources('*.sublime-syntax')` and parsing each file, but I thought the overhead would make it unappealing. (I have 117 installed, at least half of them probably built-in.) That said, we could make it a background job.

One last thing that I thought of was doing some sort of autocomplete for the values in `syntaxes`, which would only really require listing the files rather than looking at each one, but I'm not entirely sure how to do that for a single key and if you have 117, that's really clunky.

**Comment by mvastola** [comment]
A final 'one last thing': there seems to be an auto-generated file at `~/.config/sublime-text-3/Cache/Default/Syntax Summary.cache`. The name sounds extremely promising (as it would seem to remove any overhead), but I can't for the life of me figure out what file format it's in to decode it.

**Comment by mvastola** [comment]
Update: `sublime_lib` uses the parsing idea I mentioned.

**Comment by facelessuser** [comment]
> Actually, I just found this What do you think? Haven't checked how exactly it works, but this seems like a very clean solution.

1. This may be debatable, but I'm not sure we need something that lists them all. Often you are trying to write a rule to set a specific syntax, so setting the syntax manually via the command palette, and then running a quick command to get the actual syntax file name is probably more than sufficient.

2. If we wanted to do this, it is really easy without all the overhead that `sublime_lib` is doing. As you noted, using `sublime.find_resources` is all we really need we need. Looking at their example we can see that is essentially all they do as well:  https://github.com/SublimeText/sublime_lib/blob/master/st3/sublime_lib/syntax.py#L59. Ignoring the glob function, which they pass an empty pattern into, they just use `sublime.find_resources` via a fancy glob match, but in this case, they don't pass in a pattern, so it isn't even doing a glob match. All you need to do, once retrieving the files via `sublime.find_resources`, is to check the extensions.

    We don't need the custom implementation of a ResourcePath object (modeled after Python's Pathlib I imagine) etc. As someone who's written their own [glob and glob match](https://facelessuser.github.io/wcmatch/glob/#globglobmatch) library, I feel there is no need to pull in any kind of globmatch for this, not even mine 🙂. But for complex file pattern recognition 🤔...that could clean up some messy regex...

Anyways, with all of that said, I open to discuss why we think listing all the syntaxes is better than just retrieving the active one. Either one is trivial to implement, I just think getting the active view's one makes the most sense in the context of writing a syntax rule to set a specific syntax 🤷.

**Comment by facelessuser** [comment]
It seems the conversation on this has died on this. Two takeaways I got from this issue is:

1. We should at the very least in debug, log when no syntaxes are found.

   - I haven't seen a pull for this, so I guess I'll go ahead and do this.

2. Provide a helper so that a user can quickly get the full path of the syntax of their choice.

   - I may just create both helpers for people, one command that copies the current views syntax to clipboard, and another that lists them all, and when you select one, it copies it to the clipboard.

**Comment by facelessuser** [comment]
I won't consider this a bug per se. I guess I'll call it a feature request as we'll be adding some new commands.

@gir-bot remove S: triage
@gir-bot add T: feature

**Comment by facelessuser** [comment]
Turns out we did log when syntax was not found, but not if didn't have a parent directory. We were making an assumption that everyone was entering syntaxes as `package_name/path_to_file`. If we got `syntax_file`, we silently aborted.

**Comment by facelessuser** [comment]
There will be a syntax browser command and an active view command. The first will allow you to browse all syntaxes and copy them in the proper form to the clipboard, while the second will grab the syntax of the active view to the clipboard in the proper form.

I also added a comment in the settings file as discussed along with one more additional debug statement for the case you were specifically having.

This should address all issues.
