### ISSUE TITLE
Add Perl sytanx into configuration

### ISSUE THREAD

**Issue by KES777** [facelessuser/ApplySyntax#157]
```
        {
            "syntax": "Perl/Perl",
            "extensions": ["pm", "pl"],
            "rules": [
                {"interpreter": "perl"},
            ],
        },
```

**Comment by facelessuser** [comment]
Pull requests are welcome

**Comment by jfcherng** [comment]
This seems to be builtin as https://github.com/sublimehq/Packages/commit/ee0146e562094e3fd0a73722ca40fe21ff7b2007

**Comment by facelessuser** [comment]
Indeed it does

**Comment by facelessuser** [comment]
It does seem this isn't needed. Can I ask what version of Sublime you are on?

**Comment by facelessuser** [comment]
Closing as this support is already available with the stock Perl.
