### ISSUE TITLE
Formatter package interferes with ApplySyntax behaviour

### ISSUE THREAD

**Issue by macfreek** [facelessuser/ApplySyntax#158]
When I install the Formatter package, it effectively disables the ApplySyntax behaviour.

What happens is this:

    ApplySyntax: Syntax set to Ansible using Packages/Ansible/Ansible.sublime-syntax
    Formatter: Restore syntax to Packages/YAML/YAML.sublime-syntax

I think this is caused by a bug in Formatter, not in ApplySyntax, but it took me a while to figure out why ApplySyntax is not working (the second line here is something I added, it is not logged to stdout by Formatter by default). Hence I've created this report, in case others experience this problem with ApplySyntax.

The issue is reported to the Formatter package at https://github.com/bitst0rm-pub/Formatter/issues/39

**Comment by facelessuser** [comment]
Sorry, unfortunately, there is nothing I can do if some other plugin is stepping in and undoing what we are doing.

**Comment by macfreek** [comment]
I know, the only reason to file it here as well is so others who experience this issue may (hopefully) find this issue here, and get a nudge in the right direction.

**Comment by facelessuser** [comment]
Understood. If I get more complaints, I'll reference them to this issue. I do appreciate being made aware of this conflict.
