### ISSUE TITLE
Trying to configure .html files to open as Handlebars when Meteor templates

### ISSUE THREAD

**Issue by DiegeticShadow** [facelessuser/ApplySyntax#67]
Meteor apps require `.html` extensions for their templates, which are really Handlebars templates and should get Handlebars syntax highlighting. [Here’s an example](https://github.com/Differential/meteor-boilerplate/blob/master/client/templates/home/home.html). Fortunately, most Meteor templates begin with code like:
```html
<template name="home">
```
So I would think the following would let me open all Meteor templates using Handlebars syntax highlighting:
```json
				"name": "Handlebars",
				"rules": [
					{"file_name": ".*\\.html$"},
					{"first_line": "^<template name="}
```
But it doesn’t work. See also http://stackoverflow.com/questions/28413968/sublime-setting-default-syntax-for-hbs-html. Any ideas?

**Comment by facelessuser** [comment]
I will try and look at this today, but imagine there must be a configuration problem on your side.  Thanks for the example as that will help.  I will let you know if there is a bug on ApplySyntax's side.

**Comment by facelessuser** [comment]
Still haven't had time to look at this yet.  Maybe today I will have a chance if I remember.

**Comment by jguice** [comment]
Hey @DiegeticShadow maybe try Handlebars/Handlebars as the name? (or Packages/Handlebars).

**Comment by facelessuser** [comment]
@jguice, Hah, you are right, the answer was right in the link that was posted.  I haven't had a chance to look at this yet, so I haven't confirmed that this is indeed the solution.

@DiegeticShadow if you are still having issues after trying @jguice's suggestion, then please post a link to the actual syntax package you use for handlebars so we can give you the correct syntax path for `name`.

**Comment by DiegeticShadow** [comment]
Yes! Using `Handlebars/Handlebars` as the name did the trick!

In my `ApplySyntax.sublime-settings` file:

    "syntaxes": [
        {
            "name": "Handlebars/Handlebars",
            "rules": [
                {"file_name": ".*\\.html$"},
                {"first_line": "^<template name="}
            ]
        }
    ]

Thanks, I suggest adding the above to the default list of syntaxes. You’ll make a lot of Meteor developers very happy, and I can’t imagine when a normal HTML file would start with `<template name=`.

**Comment by facelessuser** [comment]
Glad you got it figured out.

> I suggest adding the above to the default list of syntaxes. You’ll make a lot of Meteor developers very happy, and I can’t imagine when a normal HTML file would start with <template name=.

If the rule is unique enough to not conflict with other syntaxs (the first line rule should ideally be specific to `Handlebars` and not other template languages), then you can issue a pull request.  Keep in mind that I don't use `Meteor`, so I will just have to take your word that it is unique.  If the rule is not unique enough, then you will have to just use it as a personal rule.

I maintain the core code, but general language rules must be provided by the community via pull requests.  I simply don't have time to add languages rules for everyone, so community participation is important.  Hopefully you will consider a pull.
