### ISSUE TITLE
Applying syntax on very first open

### ISSUE THREAD

**Issue by fabrizio5680** [facelessuser/ApplySyntax#68]
Hi,

Is there a way to apply the syntax on first open of sublime and not just new file creation. I basically want it to always be set to Javascript without having to open new file.

Thanks.

**Comment by facelessuser** [comment]
I don't understand what you mean.  Syntax is associated by view.  You have to open a view to have a syntax setting.  The setting `new_file_syntax` is used to hook into a view creation and apply the syntax.  What else are you looking for?  You want no views, but JavaScript syntax?  What would be the point if there is no view to enter your JavaScript into?

**Comment by facelessuser** [comment]
I feel that the question was answered, and the conversation appears to have ended.
