### ISSUE TITLE
Should filename used to match file_name expression have path stripped?

### ISSUE THREAD

**Issue by jguice** [facelessuser/ApplySyntax#70]
I was just trying to setup some files with no extensions as a particular syntax was confused about why it wasn't working.

After some fiddling I realized that the .* on the left-hand side of the default rules isn't just there because it's matching a variable filename, but it's also matching the path.

e.g. my attempt at a rule like this wasn't working:

`{"file_name": "myfilename$"}`

but this works:

`{"file_name": ".*/myfilename$"}`

My question is whether anyone would ever want to include path in their match (and if not maybe stripping it ahead of time would make the above more intuitive)? :)

**Comment by facelessuser** [comment]
I think your answer is right in the settings file: https://github.com/facelessuser/ApplySyntax/blob/master/ApplySyntax.sublime-settings#L96.

**Comment by jguice** [comment]
Ah, makes sense!  Thanks for finally giving folks a way to reliably syntax highlight extension-less files, etc. ;)
