### ISSUE TITLE
Improve and complete documentation.

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/ApplySyntax#72]
Use mkdocs for documentation.  Flesh out all the little rules and such and info that is either undocumented or found in the settings file but not in the readme else.

**Comment by KES777** [comment]
https://github.com/facelessuser/ApplySyntax/issues/58#issuecomment-97829947

There is problem with documentation.

http://facelessuser.github.io/ApplySyntax/usage/#name

Describe in DOC please that
"name": ["RSpec", "RSpec (snippets and syntax)/Syntaxes/RSpec"]
"RSpec" means "Packages/RSpec.tmLanguage"
"RSpec (snippets and syntax)/Syntaxes/RSpec" means "Packages/RSpec (snippets and syntax)/Syntaxes/RSpec.tmLanguage"

**Comment by facelessuser** [comment]
Will do thanks.

**Comment by KES777** [comment]
Describe please that:
"RSpec/RSpec" means "Packages/RSpec/RSpec.tmLanguage"
"RSpec (snippets and syntax)/Syntaxes/RSpec" means "Packages/RSpec (snippets and syntax)/Syntaxes/RSpec.tmLanguage"

**Comment by facelessuser** [comment]
I really do feel like it is spelled out in the docs.  I give an example of physical file path.  I explain what you put in the setting, and then show the example. I guess I could make it more obvious with `Packages/RSpec/RSpec.tmLanguage` -> `RSpec/RSpec`, but though I have not literally done that, I feel the documentation explains that this is the case; but I may give a single reference like this just to make sure everyone is clear on this point.  I don't feel like I need to iterate over every similar example though, one example is enough.

**Comment by KES777** [comment]
it is depend on your experience. You understand what is comming under hood so for you it is like 2+2.
Some one who do that first time is like kind of magic. take theme you are not common. The studying will be easier when more example you get. So on mine expierence and mine question it will be clear if you repeat example https://github.com/facelessuser/ApplySyntax/issues/72#issuecomment-98607473 in doc.

Use less words, use more examples. it will be better.

PS. I have pull request for your mistake in code. Please correct mistake in doc too:
---tmlanguage 
+++tmLanguage

Notice capital 'L'

**Comment by facelessuser** [comment]
I did add a more clear reference a moment ago, but I haven't regenerated the doc site yet; I will do that later today.  I will consider more examples.

I merged your pull request and issued a bug fix release.
