### ISSUE TITLE
Settings Key Deprecations

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/ApplySyntax#76]
- [x] Deprecate `name` key and instead use `syntax`.
- [x] Deprecate `file_name` key and instead use `file_path`.
- [x] Deprecate `binary` in favor of `interpreter` or `shebang`.

**Comment by okdana** [comment]
Submitted PR for `file_name`->`file_path`.

Do you think maybe `binary` should be deprecated in favour of `interpreter` too? Seems a lot more self-explanatory.

**Comment by facelessuser** [comment]
You got to the fast :).

> Do you think maybe binary should be deprecated in favour of interpreter too? Seems a lot more self-explanatory.

Good idea.  Maybe `shebang` is even better as that is what we are really searching for.

**Comment by facelessuser** [comment]
I guess `interpreter` could work too.  I don't know.  I guess I am open to either.

**Comment by okdana** [comment]
I dunno. I think the word 'shebang' is gross, personally, but a lot of people do use it... and it's your project obv

**Comment by facelessuser** [comment]
> I think the word 'shebang' is gross

You know, I've never thought anything about it until you just said it...now I can't un-see it.

Other variants aren't as well known like `hashbang`, so I think I'll go with `interpreter`.

**Comment by facelessuser** [comment]
`name` deprecated in commit https://github.com/facelessuser/ApplySyntax/commit/9f562fb21822c4ef91ae6d75cd07950996154b83.

**Comment by facelessuser** [comment]
Couple of tweaks for consistency in commit https://github.com/facelessuser/ApplySyntax/commit/772eaaa301d82ae880bb1370b0f05f5ce6433f85.

This wraps it up.  These will drop in the next release.
