### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by titoBouzout** [facelessuser/ApplySyntax#80]
Hi!  I'm seeing a lot of 

ApplySyntax: Syntax file for HTML does not exist at Packages/HTML/HTML.sublime-syntax
ApplySyntax: Syntax set to HTML using Packages/HTML/HTML.tmLanguage

**Comment by facelessuser** [comment]
http://facelessuser.github.io/ApplySyntax/usage/#troubleshooting-and-debugging

You can disable it if you find it annoying.

**Comment by titoBouzout** [comment]
oh the name changed? it was debug_enabled :P Thanks!

**Comment by facelessuser** [comment]
Yeah, there has been a couple of changes.  I am trying to make things a little more sensible moving forward.  Trying to document better and and make things a little more intuitive.  Hopefully it will make things a bit better and reduce the questions I get asked over and over.

**Comment by titoBouzout** [comment]
Looking pretty good, keep it up :) Thanks for the awesome packages your provide =)

**Comment by facelessuser** [comment]
Thanks!
