### ISSUE TITLE
MXML files cause false positive with default XML rules

### ISSUE THREAD

**Issue by blag** [facelessuser/ApplySyntax#82]
The default rules for XML files create a false positive with MXML files (eg: Adobe Flex apps).

MXML files use the ```<![CDATA[ ... ]>``` tags to include code, and this code should be highlighted normally. The syntax coloring for XML files does not color these files well, so this false positive gets annoying because you have to override the entire ```default_syntaxes``` setting or manually set the syntax highlighting every time you open or save a file.

This works for me, but I don't think this rule tweak handles ```.tmLanguage``` files:

    "default_syntaxes": [
        {
            // I put XML first because of files like *.tmLanguage. It is unlikely
            // that this rule will result in a false positive, meaning if it
            // matches, you probably want the XML syntax
            "name": "XML/XML",
            "extensions": ["xml.dist"],
            "rules": [
                {"file_name": ".*\\.xml(\\.dist)?$"}  // <--  Only recognize files with .xml and .xml.dist extensions
            ]
        },
        ...
    ]

I know that the number of users affected by this is small (I may very well be the only one) and Flex is (thankfully) on its way out, but tweaking this rule would be very much appreciated!

Thanks for all of your hard work! :smile:

**Comment by facelessuser** [comment]
Do MMXL files use a special extension?  If there is a way to distinguish an MMXL file from an XML file, then we can add that rule before XML and problem solved.  But hurting everyones XML recognition just to avoid one special type seems a bit backwards.

I'm open to suggestions.  But keep in mind, language rules for things I don't use only get included or modified via pull requests.

**Comment by blag** [comment]
The MXML files I've worked with have a ```mxml``` extension, so if that solves the problem: awesome!

I totally agree that messing with everybody's XML recognition for a special case is backwards. I made it an issue instead of a PR because I wasn't quite sure how to solve it in an elegant manner.

When I'm back in the office I will test out your idea and create a PR for it.

Thanks for the feedback!

**Comment by facelessuser** [comment]
It should solve it fine.  ApplySyntax goes with the first matching rule.  So if you provide a rule for mxml types right before, it should work fine.

**Comment by facelessuser** [comment]
Closing and will wait for a pull request.
