### ISSUE TITLE
Can't apply Sass Syntax

### ISSUE THREAD

**Issue by cliquenoir** [facelessuser/ApplySyntax#89]
I can't seem to get ApplySyntax working with Sass (latest version, installed via Package Control). Here's my config:
```
"syntaxes": [
    {
        "syntax": "Sass/Sass",
        "extensions": ["scss.liquid"]
    }
]
```
It seems to work fine with other syntaxes: if I, for example, swap Sass/Sass with YAML/YAML, the syntax is applied as expected to files matching the extension. 

Does this relate to how the Sass package is installed and, consequently, its install location?

Thanks in advance for the help.

**Comment by facelessuser** [comment]
I would start first by reading the docs.  They should answer most of your questions.  If you specific questions that aren't covered or aren't clear in the docs, I would post those questions here.

Here is the page covering rule creation: http://facelessuser.github.io/ApplySyntax/usage/#creating-rules.

**Comment by cliquenoir** [comment]
I did read the docs. Did you read my question?

**Comment by facelessuser** [comment]
> I did read the docs. Did you read my question?

Let's not get snarky.  I spent a lot of time putting together documentation to keep me from re-answering the same question over and over again.  Please remember that I don't get paid for support.

To answer your question, yes I did read your question: `Does this relate to how the Sass package is installed and, consequently, its install location?`, and this is covered in the docs.  I don't know what specific Sass package you have installed; therefore, I don't know how to answer your question specifically.  From the way your question is phrased it **appears** that you didn't read the part of the docs talking about how the [`syntax` attribute is configured](http://facelessuser.github.io/ApplySyntax/usage/#syntax) as it goes into details (with examples) of how you determine this value.  I would have expected a more pointed question referencing confusion about what the docs says had you read it.  Maybe you did read it, maybe you didn't.  I'm not here to point fingers, I'm just saying that I have answered the question in the docs and you should read it.

I really don't have enough info from you to say any more than that. At this point, all I can do is guess, and I guess that `Sass/Sass` is wrong.  You can't just blindly swap out the language name of interest.  Again, the docs cover [how you determine `syntax`  value](http://facelessuser.github.io/ApplySyntax/usage/#syntax).  If there is confusion about what that part of the docs says, then do feel free to elaborate here the part you don't understand, or the part that seems contradictory to your understanding, or even a case that you con't feel is covered appropriately in the docs.

**Comment by facelessuser** [comment]
It is also possible that I don't understand your question.  Maybe you can rephrase it and elaborate.

**Comment by cliquenoir** [comment]
First, apologies for coming off snarky--that wasn't my attention. Also, thanks for the prompt replies.

I did, of course, read the docs which prompted me to configure the syntax and extensions as indicated in my first comment. I installed Sass as I suspect many do, using Package Control, and I'm currently using the latest version that's available. The default location for the package is /Installed Packages/Sass.sublime-package.

After checking the console, it's clear that ApplySyntax wasn't finding Sass in /Packages/Sass because the folder did not exist. To work around the issue, I manually downloaded a copy of Sass.tmLanguage, placed it in a directory relative to Packages and now the syntax works as expected.

**Comment by facelessuser** [comment]
No worries.  No matter how you install it, it works the same.  Though thinking about it now, Package Control installs a number of packages as zip files in InstalledPackages, but you treat it the same.  InstalledPackages is treated as Packages, and the zip file is treated as the folder name minus the zip; this is how Sublime internally views zipped packages, so we treat them the same.  I guess I could mention that in the docs too.
