### ISSUE TITLE
Not working on ST3 3095 with SSH Config syntax

### ISSUE THREAD

**Issue by pzgz** [facelessuser/ApplySyntax#91]
I am trying to apply syntax SSH Config to file such as `~/.ssh/config`, the syntax was provided by https://github.com/robballou/sublimetext-sshconfig

```
    "syntaxes": [
      {
          "syntax": "SSH Config",
          "rules": [
              {"file_path": ".*config$"}
          ]
      }
```

Somehow, I opened  `~/.ssh/config` but the syntax was not applied. Checked console but with no error message and no hints indicated that ApplySyntax has detected my settings.

Am I doing something wrong?

**Comment by facelessuser** [comment]
Please see here how to configure the `syntax` key: http://facelessuser.github.io/ApplySyntax/usage/#syntax.  That will hopefully answer your question.  Look at the example it gives.

**Comment by pzgz** [comment]
Thanks @facelessuser , not sure if it's the issue, but I found the package was installed in `Installed Packages/SSH Config.sublime-package`, instead of `Packages/user/...`.

I can confirm the regex caught the path, I set it to some other syntax and I can see the syntax has been set when open the file.

**Comment by pzgz** [comment]
Yes, I copied `SSH Config` directory with the tmLanguage file in it into `Packages/Users` directory. Then the syntax will work with ApplySyntax. But I have to keep the original one which was installed into `Installed Packages` directory, otherwise the syntax won't work. Guess ST3 has changed the path for installed packages?

**Comment by facelessuser** [comment]
Package Control installs packages in `Installed Packages` as zip files unless the packages instructs Package Control to not zip the package which would then install it in `Packages` unzipped.  ApplySyntax treats both the same.  So look at the `SSH Config.sublime-package` as a folder without the extension, and look at `Installed Packages` as simply `Packages`.

So assume I had a syntax file here `Installed Packages/MyPackage.sublime-package/syntaxes/mysyntax.tmLanguage`, you would treat it as `Packages/MyPackage/syntaxes/mysyntax.tmLanguage`  which would be entered into the ApplySyntax settings file (according to the docs) as `MyPackage/syntaxes/mysyntax`.  Remember to give the full path to the syntax file, not just to the plugin folder.

Hopefully that clears things up.

**Comment by pzgz** [comment]
Thanks a lot @facelessuser , you are right, it's working now. Actually, I did thought about this before and do the changes accordingly. I think the issue is I didn't removed the `.sublime-package` extension. Thanks for your help.

**Comment by facelessuser** [comment]
Glad you got it working.  I should probably cover this case in the docs.  I will make a note of it and get it in the docs for the future.

**Comment by michaelblyons** [comment]
Future visitors might be interested in using a slightly tighter set of conditions for SSH Config:

```json
        {
            "syntax": "SSH Config/SSH Config",
            "rules": [
                {"file_path": ".*(\\\\|/)\\.ssh(\\\\|/)config$"},
                {"file_path": ".*(\\\\|/)sshd?_config($|~\\w+)"}
            ]
        }
```

This way, you don't apply it for other files ending in `config`, like `.git/config`.
