### ISSUE TITLE
Applying syntax to a new file that hasn't been saved yet

### ISSUE THREAD

**Issue by sybercorp** [facelessuser/ApplySyntax#96]
Is there a way I'm not seeing to apply a particular syntax to a new file (new tab) that hasn't actually been saved yet?

**Comment by facelessuser** [comment]
Maybe this is what you are looking for? https://github.com/facelessuser/ApplySyntax/blob/master/ApplySyntax.sublime-settings#L12

**Comment by sybercorp** [comment]
No. Thad already enabled. That only makes it default to using syntax highlighting on all new files when you save them, not new files in the sense that they're just new tabs that haven't been saved anywhere (they only exist in memory, basically), which is what I'm looking for.

Jesse Peden
239-777-6677
Threema ID: 9JY6YPKR
sybercorp@gmail.com
PGP Public Key: https://pgp.mit.edu/pks/lookup?op=get&search=0xE8C3FBF61B77E621
PGP Public Key Fingerprint: D669 3CE1 8688 BE2E A42A  14BE E8C3 FBF6 1B77 E621
(Sent from a mobile device - please excuse any typos or brevity)

**Comment by facelessuser** [comment]
I don't really understand what you are looking for.  What is it supposed to trigger off of?

If you create a new tab and copy some arbitrary text into it, how is apply syntax supposed to know?  Are you expecting it to scan and identify the code syntax on every edit event?  That would be too costly in performance not to mention detecting source syntax from analyzing text is not easy.

You would be better off manually setting the syntax.

**Comment by sybercorp** [comment]
A new tab being opened, in essence. I want all new tabs to default to a particular syntax unless I manually intervene to set it to something else.  That option only works if you save a file.

Jesse Peden
239-777-6677
Threema ID: 9JY6YPKR
sybercorp@gmail.com
PGP Public Key: https://pgp.mit.edu/pks/lookup?op=get&search=0xE8C3FBF61B77E621
PGP Public Key Fingerprint: D669 3CE1 8688 BE2E A42A  14BE E8C3 FBF6 1B77 E621
(Sent from a mobile device - please excuse any typos or brevity)

**Comment by facelessuser** [comment]
Then this is what you are looking for: https://github.com/facelessuser/ApplySyntax/blob/master/ApplySyntax.sublime-settings#L12.

You were interpreting the setting wrong.  New tabs being opened will be set to the specified syntax.  On save, traditional ApplySyntax rules will be evaluated.

Documentation on the setting is here: http://facelessuser.github.io/ApplySyntax/usage/#new-file-syntax.

**Comment by sybercorp** [comment]
If that's the case, would I just set the match logic to be blank so everything would match it?

Jesse Peden
Threema ID: 9JY6YPKR
sybercorp@gmail.com
PGP Public Key: https://pgp.mit.edu/pks/lookup?op=get&search=0xE8C3FBF61B77E621
PGP Public Key Fingerprint: D669 3CE1 8688 BE2E A42A  14BE E8C3 FBF6 1B77 E621
(Sent from a mobile device - please excuse any typos or brevity)

**Comment by facelessuser** [comment]
I'm not sure what you mean... Did you look at the documentation?  You just change the setting from false to the syntax you want to be default.

**Comment by sybercorp** [comment]
I did, which is how I have it set right now and it only takes effect when I save a file.

Right but the syntax definition has to define some sort of pattern to match against, does it not, since that syntax you're pointing it to is where you then tell it which package the language file is located in?  Can it be blank so everything would match?

Jesse Peden
Threema ID: 9JY6YPKR
sybercorp@gmail.com
PGP Public Key: https://pgp.mit.edu/pks/lookup?op=get&search=0xE8C3FBF61B77E621
PGP Public Key Fingerprint: D669 3CE1 8688 BE2E A42A  14BE E8C3 FBF6 1B77 E621
(Sent from a mobile device - please excuse any typos or brevity)

**Comment by facelessuser** [comment]
No, it has nothing to do with saving.  It occurs when a new tab is created: see code https://github.com/facelessuser/ApplySyntax/blob/master/ApplySyntax.py#L342.

**Comment by facelessuser** [comment]
There are no detect patterns or anything like that.  When a new tab is created, it just applies the specified syntax.

**Comment by sybercorp** [comment]
Okay. Thanks. Sorry, that's just different than how I got it working but I may have done unnecessary steps or something.  I'll play with it tomorrow or later tonight.

Jesse Peden
Threema ID: 9JY6YPKR
sybercorp@gmail.com
PGP Public Key: https://pgp.mit.edu/pks/lookup?op=get&search=0xE8C3FBF61B77E621
PGP Public Key Fingerprint: D669 3CE1 8688 BE2E A42A  14BE E8C3 FBF6 1B77 E621
(Sent from a mobile device - please excuse any typos or brevity)

**Comment by facelessuser** [comment]
Make sure you have it set correctly and the you don't have other plugins interfering.  It currently works fine for me.

**Comment by sybercorp** [comment]
I will. Thanks again. 99% of what I look at are Cisco configs so I want it to use that syntax unless I say otherwise, basically.

Jesse Peden
Threema ID: 9JY6YPKR
sybercorp@gmail.com
PGP Public Key: https://pgp.mit.edu/pks/lookup?op=get&search=0xE8C3FBF61B77E621
PGP Public Key Fingerprint: D669 3CE1 8688 BE2E A42A  14BE E8C3 FBF6 1B77 E621
(Sent from a mobile device - please excuse any typos or brevity)
