### ISSUE TITLE
set view syntax according to first line

### ISSUE THREAD

**Issue by ctf0** [facelessuser/ApplySyntax#97]
https://forum.sublimetext.com/t/automatically-set-view-syntax-according-to-first-line/18629

could that be done through ApplySyntax?

basically when i create a new file i just write the code am about to use so something like

`<?php` i wish if ST can automatically turn the view syntax to php, 
or 
`html` which will then turn the view syntax into html on its own,
etc...

maybe we can have like a pattern setting which if the first word is `abc` it then set the current file syntax to `xyz` :), this is more of less an extension to the **_new_file_syntax_** setting we already have.

**Comment by facelessuser** [comment]
Do you mean this? http://facelessuser.github.io/ApplySyntax/usage/#first-line-rule

**Comment by ctf0** [comment]
yes and no, 
- this have the exact functionality of what am after but i want the new unsaved file to change its syntax dynamically as u type the first line ,
where the current is only for the saved files.

**Comment by facelessuser** [comment]
I'm not sure yet how I feel about this.  I feel this feature might actually be annoying.  First line detection is only reliable on very few files.  If they have a shebang, then yeah, that might be easy, but lot's of files may not be that easy.

Then I have to async the event and limit how often it runs.  What if I don't want it to run in all unsaved views (like maybe a plugin opens up a specialized view), now I have to come up with a special flag for views to stop ApplySyntax from touching it.  But what about other people's plugins, then I have to field issues explaining to people that they now need to add a special flag to all their special plugin views to keep ApplySyntax from messing with their syntax.

Just not sure how I feel about this yet.

**Comment by ctf0** [comment]
yes i totaly understand ur point of view, the plugin should be like a Lego not an science rocket, however over the ST forum user '`kingkeith'` gave a solution and it works as expected, also @jfcherng made a plugin for that in here https://github.com/jfcherng/Sublime-AutoSetNewFileSyntax ,

so i guess this sorts out everything for this one, unless ofcourse u have some gems to interpret into this matter :heart_eyes:

**Comment by facelessuser** [comment]
I am usually selective of the features I accept.  I usually have to want the requested feature, or view it as low maintenance.  I think I've become more picky now that I maintain so many repos.

With that said, I would suggest to the person who has implemented such a plugin to limit how many characters it looks at on the first line.  I would hate to copy and paste compressed JavaScript into a new buffer and have it evaluate one giant long line on every edit.

I would also suggest they add some way to allow plugins to avoid auto detection in specific views.

I would assume this is the case, but I would make sure it only works on unsaved buffers.

Anyways, it sounds like someone had filled the request for you.  In the future I might add it if I change my mind, but, as of now, it hasn't really been a feature I have desired.

**Comment by jfcherng** [comment]
@facelessuser 
>I would suggest to the person who has implemented such a plugin to limit how many characters it looks at on the first line.
That's true. Thanks for the reminder.
