### ISSUE TITLE
Documentation: installation

### ISSUE THREAD

**Issue by sinanerdem** [facelessuser/ApplySyntax#98]
Installation docs says:

1. Ensure Package Control is installed. Instructions are found here.
2. In Sublime Text, press ctrl + shift + p (Win, Linux) or cmd + shift + p (OSX) to bring up the quick panel. It will show a list of installable plugins.
3. Start typing ApplySyntax; when you see it, select it.
4. Restart to be sure everything is loaded proper.
5. Enjoy!

But after step 2, if you dont do Package Control: Install Package, you cannot find any available plugins in the list.

**Comment by facelessuser** [comment]
True.
