### ISSUE TITLE
js.erb match by default similar to HTML ?

### ISSUE THREAD

**Issue by alkuzad** [facelessuser/ApplySyntax#99]
By default this plugin matches html.erb, should it also match js.erb ? It's by default enabled by Rails plugin from SublimeHQ.
  
    {
       // Will make .js.erb as HTML files
       "syntax": "Rails/JavaScript (Rails)",
       "extensions": ["js.erb"]
    },

**Comment by facelessuser** [comment]
I don't know.  I don't use either.  Enable it, and if it works well, issue a pull.  I only know about languages I am versed in :smile:.

**Comment by facelessuser** [comment]
If this works well for you, I am sure others may enjoy a pull request.  I am going to close this issue and await a pull request.
